#%RAML 1.0
title: financialservices-pisp
version: v1
baseUri: https://localhost:8081/api/{version}/payment
protocols: HTTPS

/initiate:
  description: |
    Initiate transfer of funds from the consumers account to a recipient account.
 
    This API will initiate an authentication and consent flow using (2-factor?) authentication following which it will initiate funds transfer.
   
    A nonce will be used to prevent replay attacks and inadvertent duplicate transfers.
   
    The payee information is provided to the API as a JWT token with the following set of payment claims. The JWT token (https://jwt.io/introduction/) is signed with the client secret of the registered app to ensure that it is not tampered with.
   
    This method redirects to the redirect_url provided as part of the inputs. It will return transaction_id and status.
    
  get:
    queryParameters:
      client_id: 
        required: true
        description: Client ID of the registered App.
      redirect_uri:
        required: true
        description: Redirect URI defined with your registered App.
      scope:
        required: true
        description: |
          Scope of the Access Token requested. Space separated list of the following options: openid, accounts, payment.
        default: openid accounts payment
      ui_locales:
        required: true
        description: Locale to be used during authorization process.
        enum: [en]
        default: en
      state:
        required: true
        description: unique ID to maintain state between asynchronous requests.
      request:
        required: true
        description: |
          The JWT token with all the relevant payment claims signed with the client secret of the app. 
          After decoding the request should provide payment info and be similar to:
          
          {
           "iss": "https://demo-merchant.example.com", //url of the JWT issuer
           "aud": "https://example-bank.cloudhub.io", //url of the party it is intended for
           "client_id": "grOmvYA89jsdhkshdIYhGtpvztofAAjz", //client id of the registered app
           "redirect_uri": "http://localhost/", //redirect uri of the app
           "scope": "openid accounts payment", //requested scopes for this call
           "state": "af0ifjsldkj", //unique state to connect request and response
           "claims": {
               "paymentinfo": {
                   "type": "sepa_credit_transfer", //transfer type
                   "to": {
                       "account_number": "62136000", //receiver account id
                       "remote_bic": "RBOSGB2109H", //receiver remote bic code
                       "remote_IBAN": "GB32ESSE40486562136016", //receiver remote iban code
                       "remote_name": "demo merchant online store" //receiver name
                   },
                   "value": {
                       "currency": "GBP", //transfer currency
                       "amount": "200" //transfer amount
                   },
                   "additional": {
                       "subject": "Online Purchase", //transfer description
                       "booking_code": "2SFBJ28553", //transfer booking code
                       "booking_date": "1462517645809", //transfer booking date
                       "value_date": "1462517645809" //transfer value date
                   },
                   "challenge_type": "SANDBOX_TAN" //challenge for additional security
               }
            }
          }
        
    responses:
      302:
        headers:
          Location:
